version: '3'
services:

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  man:
    build: .
    image: test
    ports:
      - "443:443"
      - "8443:8443"
    links:
      - mysql
    environment:
      SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_example?serverTimezone=UTC&createDatabaseIfNotExist=true:
